obstacle_range: 3.0
raytrace_range: 3.5


footprint: [[-0.405, -0.255], [-0.405, 0.255], [0.405, 0.255], [0.405, -0.255]]

inflation_radius: 0.45
cost_scaling_factor: 3.0

map_type: costmap

observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: lidar_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
